CREATE DATABASE cecilles_nstyle_db; 
USE cecilles_nstyle_db;

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `users` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`username` VARCHAR(100) UNIQUE,
	`email` VARCHAR(255) UNIQUE,
	`password_hash` VARCHAR(255) NOT NULL,
	`full_name` VARCHAR(255),
	`is_active` TINYINT(1) DEFAULT 1,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `roles` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(100) UNIQUE,
	`description` VARCHAR(255),
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `permissions` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(150) UNIQUE,
	`description` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `role_permissions` (
	`role_id` INT UNSIGNED NOT NULL,
	`permission_id` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`role_id`,`permission_id`),
	FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`) ON DELETE CASCADE,
	FOREIGN KEY (`permission_id`) REFERENCES `permissions`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `user_roles` (
	`user_id` BIGINT UNSIGNED NOT NULL,
	`role_id` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`user_id`,`role_id`),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
	FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `user_permissions` (
	`user_id` BIGINT UNSIGNED NOT NULL,
	`permission_id` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`user_id`,`permission_id`),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
	FOREIGN KEY (`permission_id`) REFERENCES `permissions`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `categories` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(150) NOT NULL,
	`description` TEXT,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `products` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`sku` VARCHAR(100) UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`description` TEXT,
	`category_id` INT UNSIGNED,
	`price` DECIMAL(12,2) DEFAULT 0.00,
	`cost` DECIMAL(12,2) DEFAULT 0.00,
	`stock_quantity` INT DEFAULT 0,
	`low_stock_threshold` INT DEFAULT 10,
	`size` VARCHAR(64),
	`color` VARCHAR(64),
	`barcode` VARCHAR(128),
	`images` JSON,
	`is_active` TINYINT(1) DEFAULT 1,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `inventory_transactions` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`product_id` BIGINT UNSIGNED NOT NULL,
	`transaction_type` ENUM('IN','OUT','ADJUST','RETURN') NOT NULL,
	`quantity` INT NOT NULL,
	`location` VARCHAR(255),
	`reference` VARCHAR(255),
	`user_id` BIGINT UNSIGNED,
	`reason` TEXT,
	`balance_after` INT,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `damaged_inventory` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`product_id` BIGINT UNSIGNED NOT NULL,
	`quantity` INT NOT NULL,
	`reason` TEXT,
	`reported_by` BIGINT UNSIGNED,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE,
	FOREIGN KEY (`reported_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `customers` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255) NOT NULL,
	`phone` VARCHAR(50),
	`email` VARCHAR(255),
	`address` TEXT,
	`notes` TEXT,
	`loyalty_points` INT DEFAULT 0,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `suppliers` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255) NOT NULL,
	`contact_person` VARCHAR(255),
	`phone` VARCHAR(50),
	`email` VARCHAR(255),
	`address` TEXT,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `purchase_orders` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`po_number` VARCHAR(100) UNIQUE,
	`supplier_id` BIGINT UNSIGNED,
	`status` ENUM('OPEN','RECEIVED','CANCELLED') DEFAULT 'OPEN',
	`expected_date` DATE,
	`total` DECIMAL(12,2) DEFAULT 0.00,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`supplier_id`) REFERENCES `suppliers`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `purchase_items` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`purchase_order_id` BIGINT UNSIGNED NOT NULL,
	`product_id` BIGINT UNSIGNED NOT NULL,
	`quantity` INT NOT NULL,
	`unit_cost` DECIMAL(12,2) DEFAULT 0.00,
	FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders`(`id`) ON DELETE CASCADE,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sales` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`sale_number` VARCHAR(100) UNIQUE,
	`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`clerk_id` BIGINT UNSIGNED,
	`customer_id` BIGINT UNSIGNED,
	`subtotal` DECIMAL(12,2) DEFAULT 0.00,
	`tax` DECIMAL(12,2) DEFAULT 0.00,
	`discount` DECIMAL(12,2) DEFAULT 0.00,
	`total` DECIMAL(12,2) DEFAULT 0.00,
	`payment_method` VARCHAR(64),
	`status` ENUM('COMPLETED','REFUNDED','CANCELLED') DEFAULT 'COMPLETED',
	`receipt_no` VARCHAR(100),
	FOREIGN KEY (`clerk_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sale_items` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`sale_id` BIGINT UNSIGNED NOT NULL,
	`product_id` BIGINT UNSIGNED,
	`qty` INT NOT NULL,
	`unit_price` DECIMAL(12,2) DEFAULT 0.00,
	`line_total` DECIMAL(12,2) DEFAULT 0.00,
	FOREIGN KEY (`sale_id`) REFERENCES `sales`(`id`) ON DELETE CASCADE,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `employees` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255) NOT NULL,
	`role` VARCHAR(100),
	`contact` VARCHAR(255),
	`hire_date` DATE,
	`pay_rate` DECIMAL(12,2) DEFAULT 0.00,
	`employment_status` ENUM('ACTIVE','INACTIVE','TERMINATED') DEFAULT 'ACTIVE',
	`bank_details` JSON,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `attendance` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`employee_id` BIGINT UNSIGNED NOT NULL,
	`date` DATE NOT NULL,
	`clock_in` TIME,
	`clock_out` TIME,
	`hours_worked` DECIMAL(5,2),
	`notes` TEXT,
	FOREIGN KEY (`employee_id`) REFERENCES `employees`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `payrolls` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`employee_id` BIGINT UNSIGNED NOT NULL,
	`period_start` DATE,
	`period_end` DATE,
	`gross_pay` DECIMAL(12,2) DEFAULT 0.00,
	`deductions` DECIMAL(12,2) DEFAULT 0.00,
	`advances` DECIMAL(12,2) DEFAULT 0.00,
	`net_pay` DECIMAL(12,2) DEFAULT 0.00,
	`status` ENUM('PENDING','PROCESSED','PAID') DEFAULT 'PENDING',
	`processed_by` BIGINT UNSIGNED,
	`processed_at` TIMESTAMP NULL,
	FOREIGN KEY (`employee_id`) REFERENCES `employees`(`id`) ON DELETE CASCADE,
	FOREIGN KEY (`processed_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `saved_reports` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255),
	`filters` JSON,
	`owner_id` BIGINT UNSIGNED,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`owner_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `audit_logs` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`user_id` BIGINT UNSIGNED,
	`action` VARCHAR(255) NOT NULL,
	`resource_type` VARCHAR(100),
	`resource_id` VARCHAR(255),
	`details` JSON,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `files` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`path` VARCHAR(1024) NOT NULL,
	`original_name` VARCHAR(255),
	`type` VARCHAR(50),
	`size` BIGINT,
	`uploaded_by` BIGINT UNSIGNED,
	`uploaded_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`uploaded_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `notifications` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`type` VARCHAR(100),
	`recipient_user_id` BIGINT UNSIGNED,
	`payload` JSON,
	`status` ENUM('PENDING','SENT','FAILED') DEFAULT 'PENDING',
	`sent_at` TIMESTAMP NULL,
	FOREIGN KEY (`recipient_user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `configs` (
	`config_key` VARCHAR(255) PRIMARY KEY,
	`config_value` TEXT,
	`last_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `api_keys` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255),
	`key` VARCHAR(255) UNIQUE,
	`permissions` JSON,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `webhooks` (
	`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255),
	`url` VARCHAR(1024),
	`events` JSON,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
