ALTER TABLE roles
  ADD COLUMN IF NOT EXISTS salary_rate DECIMAL(12,2) NOT NULL DEFAULT 0.00 AFTER description,
  ADD COLUMN IF NOT EXISTS pay_basis   ENUM('DAILY','MONTHLY') NOT NULL DEFAULT 'DAILY' AFTER salary_rate;
